name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        run: docker build -t sythilearn/front .

      - name: Push Docker image to Docker Hub
        run: docker push sythilearn/front

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_SUPPORT_HOST }}
          username: ${{ secrets.SSH_SUPPORT_USER }}
          password: ${{ secrets.SSH_SUPPORT_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker rm -f front-container || true
            docker pull sythilearn/front
            docker run -d --name front-container -p 443:443 sythilearn/front

